apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs
  template:
    metadata:
      labels:
        app: mkdocs
    spec:
      containers:
      - name: mkdocs
        image: eldarab/payslip-parser-docs
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mkdocs-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  # You can choose a port between 30000-32767
  selector:
    app: mkdocs
